### ISSUE TITLE
An compatibility problem with NPRShader plugin?

### ISSUE THREAD

**Issue by donnyjie** [krypto5863/COM3d2-AdvancedMaterialModifier#1]
![image](https://user-images.githubusercontent.com/55351646/232201721-cf829376-55aa-459e-90b8-d57c64d5ddc6.png)

My game gets stuck just before going into the main menu when error messages are shown on the BepInEx console. There may be something wrong with the version number of the NPRShader plugin.

The version of my NPRShader plugin is 0.9.3.0, and the plugin is placed in Sybaris/UnityInjector and loaded through BepInEx.UnityInjectorLoader.

**Comment by krypto5863** [comment]
Your bepinex is insanely old. Clean install CMI.

**Comment by donnyjie** [comment]
> Your bepinex is insanely old. Clean install CMI.

![image](https://user-images.githubusercontent.com/55351646/232263396-7a9c0ceb-e52a-494b-8350-52a4d9d96504.png)

Updated my bepinex but still encounter the same problem...

**Comment by krypto5863** [comment]
How are you installing NPR shader and how did you update CMI?

**Comment by donnyjie** [comment]
> How are you installing NPR shader and how did you update CMI?

I've not installed cmi. I've installed NPR shader plugin individually (plugin DLL in Sybaris/UnitiyInjector folder, loaded through BepInEx.UnityInjectorLoader).

**Comment by krypto5863** [comment]
Try the NPR in CMI?
